name: b3_news_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  dio: ^3.0.8
  flutter_dotenv: ^2.1.0
  flutter_mobx: ^1.0.1
  get: ^1.9.2
  get_it: ^3.1.0
  hive: ^1.4.0+1
  hive_flutter: ^0.3.0+1
  json_annotation: ^3.0.1
  mobx: ^1.0.2
  modal_progress_hud: ^0.1.3
  oktoast: ^2.3.1
  firebase_auth: ^0.16.0
  path_provider: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  mobx_codegen: ^1.0.2
  build_runner: ^1.7.4
  lint: ^1.1.1
  json_serializable: ^3.2.5
  hive_generator: ^0.7.0


flutter:

  uses-material-design: true

  assets:
   - assets/logo.png
   - assets/fulllogo.png
   - assets/logoandline.png
   - assets/logotitle.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
